import type { Metadata } from "next";
import { Poppins, Calligraffitti } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import React from "react";

// Initialize Poppins with weights and subsets
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],  // Example weights, adjust as needed
});

const calligraffitti = Calligraffitti({
    subsets: ["latin"],
    weight: ["400"],// Example weights, adjust as needed
});

const impact = localFont({
  src: '../../public/Impact.ttf',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
